no message

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -2,3 +2,4 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 if [ -z "$1" ]; then echo "Commit message cannot be empty" && exit 1; fi
+if [ -z "$1" ]; then echo "Commit message cannot be empty" && exit 1; fi
